feat: add message endpoint, implement e2e test
Greenstand/treetracker-queue pull request #4
Opened 2024-07-02 22:01 UTC by dagmawig

working on issue #2 

Add `DATABASE_URL` to .env file and run `test-e2e` script to do the message test.

The test sends a job to a queue with a job name and payload and fetches the job afterwards to confirm the job created.
The job is found in `pgboss` schema under `job` table.

![image](https://github.com/Greenstand/treetracker-queue/assets/61099792/ce0cfffd-32c1-4544-bd9c-a458ebd3efbf)

![image](https://github.com/Greenstand/treetracker-queue/assets/61099792/29ff3919-d8e8-41c8-85c1-2788c0a6e614)

2024-07-03 00:28 UTC, dadiorchen reviewed
This is awesome! The pgboss did exactly what I wanted: use jsonb to store the message, so in this way, in the future, we can query the message by filter easily, this is important to us.

2024-07-03 00:28 UTC, dadiorchen commented on __tests__/e2e/message.spec.js
> +})
@dagmawig please test the receiving, that is to say, you should subscribe the message queue name: 'add-tree-test' and make sure the message that you sent is received by the client.

like this:

```
it('test', done => {
  const client = new pgboss.client();
  client.subscribe('add-tree-test', data => {
    expect(data).toMatchObject({message:'ssss'});
    done();
   });
   // do the post

}}
```

2024-07-06 20:00 UTC, dagmawig commented
In this fix instead of just sending job to queue, it also completes the job and confirms the job completed.

![image](https://github.com/Greenstand/treetracker-queue/assets/61099792/e348caef-a5c8-43f8-a8c2-8dc7a141a0f1)

2024-07-20 21:48 UTC, dagmawig commented
@dadiorchen  I have replaced pg-boss with postgres listen-notify client system. For the e-2-e test I have created two separate pg clients and confirmed they both receive the notification of record insertion. We can add more functionalities in separate PRs later but I believe this will take care of the need for a proof of concept. Please review and let me know what you think.

2024-07-23 01:39 UTC, dadiorchen requested changes

2024-07-23 01:39 UTC, dadiorchen commented on __tests__/e2e/message.spec.js
> +            funQueryRes = await pgClient.query(`CREATE OR REPLACE FUNCTION queue.new_tree_notify_trigger() RETURNS TRIGGER AS $$
@dagmawig you are using `trigger` and I don't think this is good for our pub/sub model, it bind the message to the business model( trees here), for a pub/sub, it is business model agnostic and could be sent message by any client (node.js microservice), but trigger just work for tables and any db operation.

What I imagine is more like this topic: https://medium.com/@simon.white/postgres-publish-subscribe-with-nodejs-996a7e45f88

The rough test steps:
1. Create notify channel
2. To client to subscribe to the channel
3. Send message to channel by this test.
4. All the two clients received the message.

2024-08-06 03:58 UTC, dagmawig commented
Below is what the `message` table looks like. Based on the value under the `name` column, the `queue` schema function sends the message to the appropriate channel. 
![image](https://github.com/user-attachments/assets/dd2a879a-7d85-4f7b-a0e8-d51e6b63fd57)

2024-08-07 22:21 UTC, dadiorchen approved these changes

2024-08-09 15:42 UTC, merged